---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
  run_list:
  - recipe[apt]
  - recipe[opscode-dev-shim]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-10.04.box
  run_list:
  - recipe[apt]
  - recipe[opscode-dev-shim]
suites:
- name: default
  run_list:
  - recipe[opscode-pedant-test::oc-authz-pedant]
  attributes:
    pedant:
      oc-authz-pedant:
        config:
          host: "http://heimdall.opscode.us"
          port: 1234
